fixes:
  - "io/ballerina/stdlib/kafka/compiler/::./compiler-plugin/src/main/java/io/ballerina/stdlib/kafka/plugin/"

ignore:
  - "compiler-plugin-tests"
  - "examples"
  - "load-tests"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
