[package]
org = "ballerinax"
name = "kafka"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/kafka-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/kafka-clients-@kafka.version@.jar"

[[platform.java11.dependency]]
path = "./lib/kafka_2.12-@kafka.version@.jar"

[[platform.java11.dependency]]
path = "./lib/avro-@avro.version@.jar"

[build-options]
observabilityIncluded=true
