[word_count_calculator]
INPUT_TOPIC = "streams-plaintext-input"
OUTPUT_TOPIC = "streams-wordcount-output"
SSL_TRUSTSTORE_PATH = "secured-word-count-calculator/word-count-calculator/secrets/kafka.client.truststore.jks"
SSL_KEYSTORE_PATH = "secured-word-count-calculator/word-count-calculator/secrets/kafka.client.keystore.jks"
SSL_MASTER_PASSWORD = "password"
KAFKA_SECURED_URL = "localhost:9095"
SASL_USERNAME = "admin"
SASL_PASSWORD = "password"
