[package]
org = "ballerinax"
name = "kafka"
version = "3.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/kafka-native-3.0.0-SNAPSHOT.jar"
groupId = "org.ballerinalang.messaging.kafka"
artifactId = "kafka"
version = "3.0.0-SNAPSHOT"


[[platform.java11.dependency]]
path = "./lib/kafka-clients-2.8.0.jar"
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "2.8.0"


[[platform.java11.dependency]]
path = "./lib/kafka_2.12-2.8.0.jar"
groupId = "org.apache.kafka"
artifactId = "kafka_2.12"
version = "2.8.0"


[[platform.java11.dependency]]
path = "./lib/avro-1.9.2.jar"
groupId = "org.apache.avro"
artifactId = "avro"
version = "1.9.2"

[build-options]
observabilityIncluded=true
