[package]
org = "ballerinax"
name = "kafka"
version = "3.6.0"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming", "network", "messaging"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "kafka-native"
version = "3.6.0"
path = "../native/build/libs/kafka-native-3.6.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/kafka-clients-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/kafka_2.12-2.8.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.1.0"
path = "./lib/constraint-native-1.1.0-20221122-134300-fc2d3aa.jar"

[build-options]
observabilityIncluded=true
