[package]
org = "ballerinax"
name = "kafka"
version = "3.1.0"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming", "network", "messaging"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/kafka-native-3.1.0.jar"

[[platform.java11.dependency]]
path = "./lib/kafka-clients-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/kafka_2.12-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/avro-1.9.2.jar"

[build-options]
observabilityIncluded=true
