name: Create Automated Summary PR for Load Tests
on:
  push:
    branches:
      - 'nightly-**'
    paths:
      - 'load-tests/**/results/summary.csv'
jobs:
  createPullRequest:
    name: Create Summary Update PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check for existing PRs
        id: checkPRs
        shell: bash
        run: printf "::set-output name=prNotExists::%s" $(gh pr list --json headRefName --jq 'isempty(.[]| .headRefName | match("nightly-"))')
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
      - name: Create pull request for new summary
        if: ${{ steps.checkPRs.outputs.prNotExists == 'true' }}
        run: gh pr create --title "[Automated] Update summary csv files" --body "Update summary csv files"
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
